site_name: SmartHub
site_url: "https://github.com/fslef/SmartHub"
repo_name: "fslef/SmartHub"
repo_url: "https://github.com/fslef/SmartHub"
edit_uri: "edit/mainline/site/content"
docs_dir: ".."
site_dir: "../../site"

# nav:
#   - Home: 'index.fr.md'
#   - Infrastructure:
#     - Virtualisation: 'virtualisation/virtualisation-home.fr.md'
#     - Hardware: 'hardware/hardware-home.fr.md'
#   - Network: 'network/network-home.fr.md'
#   - Network-Configuration: 'network-config/network-configuration.fr.md'

theme:
  name: material
  palette:
    primary: blue
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: material/home-automation
  language: fr
  #features:
    # - tabs
    # - instant
    # - navigation.tabs
    # - navigation.sections

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - info
  - i18n:
      languages:
        - locale: fr
          name: Français
          build: true
          default: true
        - locale: en
          name: English
          build: true
