site_name: SmartHub
site_description: 'Develop, Release and Operate Container Apps on AWS.'
site_url: 'https://github.com/fslef/SmartHub'
repo_name: 'aws/copilot-cli'
repo_url: 'https://github.com/fslef/SmartHub'
edit_uri: 'edit/mainline/site/content'
docs_dir: '..'
site_dir: '../../site'

nav:
  - Home: index.en.md

theme:
  name: material
  palette:
    primary: blue
  font: false
  icon:
    logo: material-home-automation
  language: fr
  features:
    - tabs
    - instant
    - navigation.tabs

markdown_extensions:
  - meta

plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        - locale: fr
          name: Français
          build: true
          default_language: true
        - locale: en
          name: English
          build: true
      material_alternate: false