site_name: SmartHub
site_description: "Develop, Release and Operate Container Apps on AWS."
site_url: "https://github.com/fslef/SmartHub"
repo_name: "fslef/SmartHub"
repo_url: "https://github.com/fslef/SmartHub"
edit_uri: "edit/mainline/site/content"
docs_dir: ".."
site_dir: "../../site"

nav:
  - Home: index.fr.md

theme:
  name: material
  palette:
    primary: blue
  font: false
  icon:
    logo: material/home-automation
  language: fr
  features:
    - tabs
    - instant
    - navigation.tabs
    - icons

markdown_extensions:
  - meta
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search
  - i18n:
      languages:
        - locale: fr
          name: Français
          build: true
          default: true
        - locale: en
          name: English
          build: true
