site_name: SmartHub
site_url: "https://github.com/fslef/SmartHub"
repo_name: "fslef/SmartHub"
repo_url: "https://github.com/fslef/SmartHub"
edit_uri: "edit/main/docs/"
docs_dir: ".."
site_dir: "../../site"

theme:
  name: material
  palette:
    primary: blue
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: material/home-automation
  language: fr
  features:
    - content.action.edit

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - i18n:
      languages:
        - locale: fr
          name: Français
          build: true
          default: true
        - locale: en
          name: English
          build: true
